
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[302] =
    {   0,
        0,    0,    0,    0,   87,   79,   71,   71,   18,   79,
       61,   25,   22,   79,   12,   13,   23,   10,    8,   11,
       79,   24,   63,   63,    7,    4,   14,    9,   15,   61,
       61,   61,   16,   19,   17,   21,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,    5,   20,    6,   26,   79,   82,   82,   85,   85,
       71,   70,   69,   70,    0,   61,    0,    0,   66,   78,
       77,   65,   62,   63,    0,    0,    1,    2,    3,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   39,   61,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   61,    0,    0,
        0,   82,   83,   81,   84,   80,   70,    0,   69,   70,
       70,    0,   68,   68,    0,    0,    0,   77,   65,    0,
        0,   67,   64,   61,   61,   61,   27,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   46,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,    0,    0,    0,   70,   70,   70,
        0,    0,    0,    0,   66,    0,   65,   61,   61,   59,
       61,   61,   30,   31,   61,   61,   61,   61,   36,   61,
       61,   61,   61,   42,   61,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   57,   76,    0,
        0,    0,   70,   70,    0,    0,    0,   60,   61,   61,
       61,   32,   61,   61,   61,   61,   38,   40,   61,   61,
       44,   61,   61,   61,   61,   50,   61,   61,   61,   61,
       56,   61,    0,    0,    0,   70,    0,    0,    0,   58,
       61,   61,   61,   61,   35,   61,   61,   43,   45,   47,
       61,   61,   51,   52,   53,   61,   61,    0,    0,    0,
        0,   70,   75,   61,   29,   33,   34,   61,   61,   61,
       61,   54,   61,    0,    0,   73,    0,   61,   61,   61,
       48,   49,   55,    0,    0,   72,   28,   37,   41,   74,

        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,    1,    1,   27,   28,   28,   28,   29,   30,
        7,    7,    7,    7,    7,   31,    7,    7,   32,    7,
        7,   33,   34,   35,   36,    7,    7,   37,    7,    7,
       38,   39,   40,   41,    7,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,    7,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,    7,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[70] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    4,
        1,    1,    5,    1,    1,    1,    1,    5,    6,    6,
        6,    1,    1,    1,    1,    1,    6,    6,    6,    6,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1,
        1,    6,    6,    6,    6,    6,    6,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[319] =
    {   0,
        0,  554,   67,   68,  559,  561,   70,   73,   73,  554,
        0,  561,  561,  518,  561,  561,  561,  561,  561,  561,
       63,   74,   74,   79,  534,  561,  531,  561,  528,  526,
      509,  518,  561,  561,  561,  561,   47,  495,   55,   33,
       51,  497,  494,  492,  491,   62,   67,   68,  480,  490,
      488,  561,  561,  561,  561,   85,    0,    0,  524,  528,
      130,   85,  561,  140,  127,    0,  530,  146,  132,  561,
        0,  143,  154,  165,  176,    0,  561,  561,  561,  508,
      487,  501,  471,  475,  479,  474,  490,  477,  483,  468,
      467,  483,  471,   66,  471,  479,  463,  476,  461,  470,

      477,  461,  462,  458,  465,  458,   68,  463,  148,  467,
      453,    0,  561,  561,  561,  561,  200,  206,   97,  193,
      241,  195,  561,  500,  120,  499,  203,    0,  206,  217,
      209,  221,    0,  474,  461,  477,    0,  447,  452,  457,
      444,   95,  459,  457,  446,  452,  455,  435,  449,  446,
      432,  446,  428,    0,  431,  444,  427,  429,  120,  426,
      439,  429,  420,  416,  244,  406,  407,  253,  262,  296,
      438,  224,  418,  230,  255,  258,  270,  392,  372,    0,
      365,  363,    0,    0,  335,  348,  332,  340,    0,  335,
      330,  329,  330,    0,  335,  326,  343,  334,  324,  332,

      317,  322,  322,  321,  319,  309,  314,    0,  561,  356,
      306,  311,  152,  325,  353,  347,  346,    0,  291,  307,
      307,    0,  284,  295,  291,  276,    0,    0,  288,  288,
        0,  268,  273,  277,  276,    0,  281,  268,  278,  276,
        0,  267,  308,  252,  258,  354,  305,  306,  298,    0,
      246,  252,  245,  244,    0,  253,  258,    0,    0,    0,
      247,  254,    0,    0,    0,  250,  250,  261,  173,  256,
      212,  182,  561,  193,    0,    0,    0,  165,  174,  141,
      147,    0,  143,  274,  177,  561,  155,  104,   83,   83,
        0,    0,    0,  299,  119,  561,    0,    0,    0,  561,

      561,  401,  407,  411,  417,  423,  429,  435,  441,  113,
      444,  447,  453,  456,  462,  465,  471,  477
    } ;

static yyconst flex_int16_t yy_def[319] =
    {   0,
      301,    1,  302,  302,  301,  301,  301,  301,  303,  301,
      304,  301,  301,  305,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  304,
      304,  304,  301,  301,  301,  301,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  301,  301,  301,  301,  301,  306,  306,  307,  308,
      301,  303,  301,  303,  301,  304,  301,  305,  301,  301,
      309,  301,  301,  301,  301,  310,  301,  301,  301,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,

      304,  304,  304,  304,  304,  304,  304,  304,  301,  301,
      301,  306,  301,  301,  301,  301,  303,  301,  303,  303,
      303,  301,  301,  301,  301,  311,  301,  309,  301,  301,
      301,  301,  310,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  301,  301,  301,  303,  303,  121,
      301,  301,  312,  301,  301,  301,  301,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,

      304,  304,  304,  304,  304,  304,  304,  304,  301,  301,
      301,  301,  303,  121,  313,  301,  314,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  315,  301,  301,  121,  313,  301,  316,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  315,  301,  317,
      301,  303,  301,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  301,  317,  301,  318,  304,  304,  304,
      304,  304,  304,  301,  318,  301,  304,  304,  304,  301,

        0,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301
    } ;

static yyconst flex_int16_t yy_nxt[631] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       24,   25,   26,   27,   28,   29,   11,   11,   11,   30,
       11,   31,   11,   11,   32,   11,   11,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   11,   11,   43,
       11,   44,   45,   11,   46,   11,   11,   47,   48,   49,
       50,   51,   11,   11,   11,   52,   53,   54,   55,   58,
       58,   61,   61,   61,   61,   61,   61,   63,   89,   59,
       59,   69,   69,   69,   60,   60,   70,   90,  109,   63,
       72,   71,   73,   73,   74,   72,   86,   74,   74,   74,

       83,   63,   75,   87,   91,   97,   84,   75,  100,   88,
       76,   64,  101,  102,   92,   98,  103,  162,  133,   75,
      148,  296,   99,   64,   75,  149,  163,  104,  299,  123,
      105,   61,   61,   61,  110,   64,  298,   76,  172,  172,
      111,  117,  118,  117,  119,  122,  122,  122,  301,  297,
       69,   69,   69,  185,  186,  124,   63,  296,  120,  120,
      127,  129,  129,  129,  125,  125,  165,  165,  165,  202,
       72,  130,   73,   73,   74,  273,  284,  127,   64,  286,
      203,   72,   75,   74,   74,   74,   63,  293,  130,  131,
       64,  131,  292,   75,  132,  132,  132,   63,  171,   75,

      121,  117,  118,  117,   63,  291,  126,  118,  118,  118,
       75,  169,  169,  122,  122,  122,  174,  290,  174,  289,
       64,  175,  175,  175,  129,  129,  129,  132,  132,  132,
      176,   64,  176,  123,  130,  177,  177,  177,  168,  132,
      132,  132,  216,  216,   62,   63,  209,  210,  175,  175,
      175,  130,  288,  287,  117,  118,  117,  119,  286,  170,
      170,  170,  165,  165,  165,  269,   63,  170,  170,  170,
      170,  120,  120,  175,  175,  175,  177,  177,  177,   64,
      213,  213,  170,  170,  170,  170,  170,  170,  177,  177,
      177,   64,  294,  294,  294,  283,  282,  281,  280,  279,

       64,  300,  278,  277,  276,  275,  274,  123,  273,  248,
      271,  270,  269,  121,  214,  214,  214,  294,  294,  294,
      267,  266,  214,  214,  214,  214,  265,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  255,  214,  214,  214,
      214,  214,  214,  246,  246,  246,  254,  253,  252,  251,
      250,  246,  246,  246,  246,  123,  123,  248,  245,  244,
      243,  242,  241,  240,  239,  238,  246,  246,  246,  246,
      246,  246,  272,  272,  272,  237,  236,  235,  234,  233,
      272,  272,  272,  272,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  272,  272,  272,  272,  272,

      272,   57,   57,   57,   57,   57,   57,   62,  221,   62,
       62,   62,   62,   66,  220,  219,   66,   67,   67,   67,
      218,   67,   67,  112,  112,  112,  112,  123,  112,  113,
      113,  113,  113,  113,  113,  115,  115,  115,  115,  115,
      115,  128,  215,  128,  128,  128,  128,  173,  212,  173,
      217,  211,  217,  247,  247,  247,  247,  247,  247,  249,
      208,  249,  268,  268,  268,  268,  268,  268,   67,  207,
       67,  285,  285,  285,  285,  285,  285,  295,  295,  295,
      295,  295,  295,  206,  205,  204,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,

      187,  184,  183,  182,  181,  180,  179,  178,  123,  123,
      167,  166,  164,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  134,  123,
      116,  114,  108,  107,  106,   96,   95,   94,   93,   85,
       82,   81,   80,   79,   78,   77,   68,   65,  301,   56,
        5,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301
    } ;

static yyconst flex_int16_t yy_chk[631] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    7,    7,    7,    8,    8,    8,    9,   40,    3,
        4,   21,   21,   21,    3,    4,   22,   40,   56,   62,
       23,   22,   23,   23,   23,   24,   39,   24,   24,   24,

       37,  119,   23,   39,   41,   46,   37,   24,   47,   39,
       23,    9,   47,   48,   41,   46,   48,  107,  310,   23,
       94,  295,   46,   62,   24,   94,  107,   48,  290,  125,
       48,   61,   61,   61,   56,  119,  289,   23,  125,  125,
       56,   64,   64,   64,   64,   65,   65,   65,   68,  288,
       69,   69,   69,  142,  142,   68,  213,  287,   64,   64,
       69,   72,   72,   72,   68,   68,  109,  109,  109,  159,
       73,   72,   73,   73,   73,  269,  269,   69,   64,  285,
      159,   74,   73,   74,   74,   74,  272,  283,   72,   75,
      213,   75,  281,   74,   75,   75,   75,  120,  122,   73,

       64,  117,  117,  117,  117,  280,   68,  118,  118,  118,
       74,  120,  120,  122,  122,  122,  127,  279,  127,  278,
      272,  127,  127,  127,  129,  129,  129,  131,  131,  131,
      130,  120,  130,  172,  129,  130,  130,  130,  117,  132,
      132,  132,  172,  172,  118,  121,  165,  165,  174,  174,
      174,  129,  274,  271,  168,  168,  168,  168,  270,  121,
      121,  121,  165,  165,  165,  268,  169,  121,  121,  121,
      121,  168,  168,  175,  175,  175,  176,  176,  176,  121,
      169,  169,  121,  121,  121,  121,  121,  121,  177,  177,
      177,  168,  284,  284,  284,  267,  266,  262,  261,  257,

      169,  294,  256,  254,  253,  252,  251,  249,  248,  247,
      245,  244,  243,  168,  170,  170,  170,  294,  294,  294,
      242,  240,  170,  170,  170,  170,  239,  238,  237,  235,
      234,  233,  232,  230,  229,  226,  225,  170,  170,  170,
      170,  170,  170,  214,  214,  214,  224,  223,  221,  220,
      219,  214,  214,  214,  214,  217,  216,  215,  212,  211,
      210,  207,  206,  205,  204,  203,  214,  214,  214,  214,
      214,  214,  246,  246,  246,  202,  201,  200,  199,  198,
      246,  246,  246,  246,  197,  196,  195,  193,  192,  191,
      190,  188,  187,  186,  185,  246,  246,  246,  246,  246,

      246,  302,  302,  302,  302,  302,  302,  303,  182,  303,
      303,  303,  303,  304,  181,  179,  304,  305,  305,  305,
      178,  305,  305,  306,  306,  306,  306,  173,  306,  307,
      307,  307,  307,  307,  307,  308,  308,  308,  308,  308,
      308,  309,  171,  309,  309,  309,  309,  311,  167,  311,
      312,  166,  312,  313,  313,  313,  313,  313,  313,  314,
      164,  314,  315,  315,  315,  315,  315,  315,  316,  163,
      316,  317,  317,  317,  317,  317,  317,  318,  318,  318,
      318,  318,  318,  162,  161,  160,  158,  157,  156,  155,
      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,

      143,  141,  140,  139,  138,  136,  135,  134,  126,  124,
      111,  110,  108,  106,  105,  104,  103,  102,  101,  100,
       99,   98,   97,   96,   95,   93,   92,   91,   90,   89,
       88,   87,   86,   85,   84,   83,   82,   81,   80,   67,
       60,   59,   51,   50,   49,   45,   44,   43,   42,   38,
       32,   31,   30,   29,   27,   25,   14,   10,    5,    2,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "idl.lex"
#line 2 "idl.lex"
// import YYtokentypes;
import YYtokentypes;

#line 705 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 19 "idl.lex"


#line 899 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 302 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 561 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 23 "idl.lex"
{ yyreturn(RESOLVE_TOKEN); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 24 "idl.lex"
{ yyreturn(SHIFTLEFT_TOKEN); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 25 "idl.lex"
{ yyreturn(SHIFTRIGHT_TOKEN); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 26 "idl.lex"
{ yyreturn(';');} 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "idl.lex"
{ yyreturn(LBRACE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "idl.lex"
{ yyreturn(RBRACE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "idl.lex"
{ yyreturn(':'); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 30 "idl.lex"
{ yyreturn(','); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 31 "idl.lex"
{ yyreturn('='); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 32 "idl.lex"
{ yyreturn('+'); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 33 "idl.lex"
{ yyreturn('-'); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 34 "idl.lex"
{ yyreturn('('); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 35 "idl.lex"
{ yyreturn(')'); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 36 "idl.lex"
{ yyreturn('<'); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 37 "idl.lex"
{ yyreturn('>'); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 38 "idl.lex"
{ yyreturn('['); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 39 "idl.lex"
{ yyreturn(']'); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 40 "idl.lex"
{ yyreturn('\"'); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 41 "idl.lex"
{ yyreturn('\\'); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 42 "idl.lex"
{ yyreturn('|'); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 43 "idl.lex"
{ yyreturn('^'); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 44 "idl.lex"
{ yyreturn('&'); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 45 "idl.lex"
{ yyreturn('*'); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 46 "idl.lex"
{ yyreturn('/'); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 47 "idl.lex"
{ yyreturn('%'); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 48 "idl.lex"
{ yyreturn('~'); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 50 "idl.lex"
{ yyreturn(ANY_TOKEN); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 51 "idl.lex"
{ yyreturn(ATTRIBUTE_TOKEN); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 52 "idl.lex"
{ yyreturn(BOOLEAN_TOKEN); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 53 "idl.lex"
{ yyreturn(CASE_TOKEN); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 54 "idl.lex"
{ yyreturn(CHAR_TOKEN); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 55 "idl.lex"
{ yyreturn(CONST_TOKEN); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 56 "idl.lex"
{ yyreturn(CONTEXT_TOKEN); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 57 "idl.lex"
{ yyreturn(DEFAULT_TOKEN); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 58 "idl.lex"
{ yyreturn(DOUBLE_TOKEN); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 59 "idl.lex"
{ yyreturn(ENUM_TOKEN); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 60 "idl.lex"
{ yyreturn(EXCEPTION_TOKEN); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 61 "idl.lex"
{ yyreturn(FLOAT_TOKEN); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 62 "idl.lex"
{ yyreturn(IN_TOKEN); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 63 "idl.lex"
{ yyreturn(INOUT_TOKEN); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 64 "idl.lex"
{ yyreturn(INTERFACE_TOKEN); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 65 "idl.lex"
{ yyreturn(LONG_TOKEN); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 66 "idl.lex"
{ yyreturn(MODULE_TOKEN); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 67 "idl.lex"
{ yyreturn(OCTET_TOKEN); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 68 "idl.lex"
{ yyreturn(ONEWAY_TOKEN); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 69 "idl.lex"
{ yyreturn(OUT_TOKEN); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 70 "idl.lex"
{ yyreturn(RAISES_TOKEN); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 71 "idl.lex"
{ yyreturn(READONLY_TOKEN); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 72 "idl.lex"
{ yyreturn(SEQUENCE_TOKEN); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 73 "idl.lex"
{ yyreturn(SHORT_TOKEN); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 74 "idl.lex"
{ yyreturn(STRING_TOKEN); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 75 "idl.lex"
{ yyreturn(STRUCT_TOKEN); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 76 "idl.lex"
{ yyreturn(SWITCH_TOKEN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 77 "idl.lex"
{ yyreturn(TYPEDEF_TOKEN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 78 "idl.lex"
{ yyreturn(UNSIGNED_TOKEN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 79 "idl.lex"
{ yyreturn(UNION_TOKEN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 80 "idl.lex"
{ yyreturn(VOID_TOKEN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 81 "idl.lex"
{ yyreturn(OBJECT_TOKEN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 82 "idl.lex"
{ yyreturn(BOOLEAN_LITERAL); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 83 "idl.lex"
{ yyreturn(BOOLEAN_LITERAL); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 86 "idl.lex"
{ /* identifier */
		yyreturn(IDENTIFIER);
		}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 90 "idl.lex"
{/* octal */
		yyreturn(INTEGER_LITERAL); 
		}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 94 "idl.lex"
{ /* decimal */
		yyreturn(INTEGER_LITERAL);
		}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 98 "idl.lex"
{ /* hex */
		yyreturn(INTEGER_LITERAL);
		}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 102 "idl.lex"
{ /* float 0.e0 */
		yyreturn(FLOAT_LITERAL);
		}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 106 "idl.lex"
{ /* float .0e0 */
		yyreturn(FLOAT_LITERAL);
		}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "idl.lex"
{ /* float 0e-0 */
		yyreturn(FLOAT_LITERAL);   
		}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 114 "idl.lex"
{ /* quoted char */
		yyreturn(CHARACTER_LITERAL);
		}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 118 "idl.lex"
{ /* string */
		yyreturn(STRING_LITERAL);
		}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 121 "idl.lex"
{ yylexerror("unclosed string");}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 123 "idl.lex"
{ /*  eliminate white space  */ }
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 125 "idl.lex"
{ yyreturn(PRAGMA_INFO);}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 126 "idl.lex"
{ yyreturn(IDENT_INFO);}
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 127 "idl.lex"
{ 
		yyreturn(LINE_AND_FILE_INFO);
		}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 130 "idl.lex"
{
		yyreturn(LINE_AND_FILE_INFO);
		}
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 133 "idl.lex"
{
		yyreturn(LINE_AND_FILE_INFO);
		}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 137 "idl.lex"
{ /*   uni-line comment */ }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 138 "idl.lex"
{ yybegin(COMMENT); comment_depth++;  }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 140 "idl.lex"
{ yylexerror("Illegal character: " + ((int)yytext.currentchar()));}
	YY_BREAK


case 80:
YY_RULE_SETUP
#line 145 "idl.lex"
{ /* begin nested multiline comment */ comment_depth++; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 146 "idl.lex"
{ /* end multiline comment */
		comment_depth--;
		if (comment_depth == 0) { yybegin(INITIAL); }
		}
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 151 "idl.lex"
{}
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 152 "idl.lex"
{}
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 153 "idl.lex"
{}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 155 "idl.lex"
{ yylexerror("Illegal character in comment: " + ((int)yytext.currentchar())); }
	YY_BREAK

case 86:
YY_RULE_SETUP
#line 158 "idl.lex"
ECHO;
	YY_BREAK
#line 1455 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 302 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 302 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 301);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 158 "idl.lex"



// Include the set of tokentypes to 
// avoid having to say e.g. Tokentypes.INTEGER_LITERAL

// TOKENTYPES

@TOKENTYPES@

protected static final char LBRACE = '{';
protected static final char RBRACE = '}';
protected int comment_depth = 0;

