macro(check_boost)
    if(WIN32)
        option(EPROSIMA_BOOST "Activate special set of BOOST_LIBRARYDIR" OFF)
        if(EPROSIMA_BUILD)
            set(EPROSIMA_BOOST ON)
        endif()
    endif()

    # Find package Boost
    set(Boost_USE_STATIC_LIBS OFF)
    set(Boost_USE_MULTITHREADED ON)
    set(Boost_USE_STATIC_RUNTIME OFF)
    if(WIN32)
        set(BOOST_LIBRARYDIR_ $ENV{BOOST_LIBRARYDIR})
        if(BOOST_LIBRARYDIR_)
            if(EPROSIMA_BOOST)
                file(TO_CMAKE_PATH "${BOOST_LIBRARYDIR_}/${MSVC_ARCH}" BOOST_LIBRARYDIR)
            else()
                file(TO_CMAKE_PATH "${BOOST_LIBRARYDIR_}" BOOST_LIBRARYDIR)
            endif()
        endif()
    endif()
    find_package(Boost REQUIRED COMPONENTS ${ARGN})
    if(NOT Boost_FOUND)
        message(FATAL_ERROR "Cannot find Boost components: ${ARGN}")
    endif()
endmacro()

macro(install_boost)
    if(MSVC OR MSVC_IDE)
        foreach(arg_ ${ARGN})
            if(EPROSIMA_BUILD)
                string(TOUPPER ${arg_} boost_lib_) 
		string(REPLACE ".lib" ".dll" boost_lib_release_ ${Boost_${boost_lib_}_LIBRARY_RELEASE})
		install(FILES ${boost_lib_release_}
                    DESTINATION ${BIN_INSTALL_DIR}
                    COMPONENT binaries
                    CONFIGURATIONS Release
                    )
            endif()
        endforeach()
    endif()
endmacro()
