#line 2 "IDLScanner.cc"

#line 4 "IDLScanner.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* begin standard C++ headers. */
#include <iostream> 
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
/* %endif */

/* %if-c++-only */
	std::istream* yy_input_file;
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */
/* %if-not-reentrant */
/* %not-for-header */

/* %ok-for-header */

/* %endif */
/* %endif */

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

#define yytext_ptr yytext

#include "FlexLexer.h"

/* %if-c-only Standard (non-C++) definition */
/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 85
#define YY_END_OF_BUFFER 86
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[301] =
    {   0,
        0,    0,    0,    0,   86,   78,   70,   70,   18,   78,
       60,   25,   22,   78,   12,   13,   23,   10,    8,   11,
       78,   24,   62,   62,    7,    4,   14,    9,   15,   60,
       60,   60,   16,   19,   17,   21,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,    5,   20,    6,   78,   81,   81,   84,   84,   70,
       69,   68,   69,    0,   60,    0,    0,   65,   77,   76,
       64,   61,   62,    0,    0,    1,    2,    3,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   38,   60,   60,   60,   60,   60,   60,   60,

       60,   60,   60,   60,   60,   60,   60,    0,    0,    0,
       81,   82,   80,   83,   79,   69,    0,   68,   69,   69,
        0,   67,   67,    0,    0,    0,   76,   64,    0,    0,
       66,   63,   60,   60,   60,   26,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   45,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,    0,    0,    0,   69,   69,   69,    0,
        0,    0,    0,   65,    0,   64,   60,   60,   58,   60,
       60,   29,   30,   60,   60,   60,   60,   35,   60,   60,
       60,   60,   41,   60,   60,   60,   60,   60,   60,   60,

       60,   60,   60,   60,   60,   60,   56,   75,    0,    0,
        0,   69,   69,    0,    0,    0,   59,   60,   60,   60,
       31,   60,   60,   60,   60,   37,   39,   60,   60,   43,
       60,   60,   60,   60,   49,   60,   60,   60,   60,   55,
       60,    0,    0,    0,   69,    0,    0,    0,   57,   60,
       60,   60,   60,   34,   60,   60,   42,   44,   46,   60,
       60,   50,   51,   52,   60,   60,    0,    0,    0,    0,
       69,   74,   60,   28,   32,   33,   60,   60,   60,   60,
       53,   60,    0,    0,   72,    0,   60,   60,   60,   47,
       48,   54,    0,    0,   71,   27,   36,   40,   73,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,    1,    1,   27,   28,   28,   28,   29,   30,
        7,    7,    7,    7,    7,   31,    7,    7,   32,    7,
        7,   33,   34,   35,   36,    7,    7,   37,    7,    7,
       38,   39,   40,   41,    7,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,    7,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,    7,   66,   67,   68,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[69] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    4,
        1,    1,    5,    1,    1,    1,    1,    5,    6,    6,
        6,    1,    1,    1,    1,    1,    6,    6,    6,    6,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1,
        1,    6,    6,    6,    6,    6,    6,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[318] =
    {   0,
        0,  553,   66,   67,  558,  560,   69,   72,   72,  553,
        0,  560,  560,  517,  560,  560,  560,  560,  560,  560,
       62,   73,   73,   78,  533,  560,  530,  560,  527,  525,
      508,  517,  560,  560,  560,  560,   46,  494,   54,   32,
       50,  496,  493,  491,  490,   61,   66,   67,  479,  489,
      487,  560,  560,  560,   84,    0,    0,  523,  527,  129,
       84,  560,  139,  126,    0,  529,  145,  131,  560,    0,
      142,  153,  164,  175,    0,  560,  560,  560,  507,  486,
      500,  470,  474,  478,  473,  489,  476,  482,  467,  466,
      482,  470,   65,  470,  478,  462,  475,  460,  469,  476,

      460,  461,  457,  464,  457,   67,  462,  147,  466,  452,
        0,  560,  560,  560,  560,  199,  205,   96,  192,  240,
      194,  560,  499,  119,  498,  202,    0,  205,  216,  208,
      220,    0,  473,  460,  476,    0,  446,  451,  456,  443,
       94,  458,  456,  445,  451,  454,  434,  448,  445,  431,
      445,  427,    0,  430,  443,  426,  428,  119,  425,  438,
      428,  419,  415,  243,  405,  406,  252,  261,  295,  437,
      223,  417,  229,  254,  257,  269,  391,  371,    0,  364,
      362,    0,    0,  334,  347,  331,  339,    0,  334,  329,
      328,  329,    0,  334,  325,  342,  333,  323,  331,  316,

      321,  321,  320,  318,  308,  313,    0,  560,  355,  305,
      310,  151,  324,  352,  346,  345,    0,  290,  306,  306,
        0,  283,  294,  290,  275,    0,    0,  287,  287,    0,
      267,  272,  276,  275,    0,  280,  267,  277,  275,    0,
      266,  307,  251,  257,  353,  304,  305,  297,    0,  245,
      251,  244,  243,    0,  252,  257,    0,    0,    0,  246,
      253,    0,    0,    0,  249,  249,  260,  172,  255,  211,
      181,  560,  192,    0,    0,    0,  164,  173,  140,  146,
        0,  142,  273,  176,  560,  154,  103,   82,   82,    0,
        0,    0,  298,  118,  560,    0,    0,    0,  560,  560,

      400,  406,  410,  416,  422,  428,  434,  440,  112,  443,
      446,  452,  455,  461,  464,  470,  476
    } ;

static yyconst flex_int16_t yy_def[318] =
    {   0,
      300,    1,  301,  301,  300,  300,  300,  300,  302,  300,
      303,  300,  300,  304,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  303,
      303,  303,  300,  300,  300,  300,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  300,  300,  300,  300,  305,  305,  306,  307,  300,
      302,  300,  302,  300,  303,  300,  304,  300,  300,  308,
      300,  300,  300,  300,  309,  300,  300,  300,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,

      303,  303,  303,  303,  303,  303,  303,  300,  300,  300,
      305,  300,  300,  300,  300,  302,  300,  302,  302,  302,
      300,  300,  300,  300,  310,  300,  308,  300,  300,  300,
      300,  309,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  300,  300,  300,  302,  302,  120,  300,
      300,  311,  300,  300,  300,  300,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,

      303,  303,  303,  303,  303,  303,  303,  300,  300,  300,
      300,  302,  120,  312,  300,  313,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  314,  300,  300,  120,  312,  300,  315,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  314,  300,  316,  300,
      302,  300,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  300,  316,  300,  317,  303,  303,  303,  303,
      303,  303,  300,  317,  300,  303,  303,  303,  300,    0,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300
    } ;

static yyconst flex_int16_t yy_nxt[629] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       24,   25,   26,   27,   28,   29,   11,   11,   11,   30,
       11,   31,   11,   11,   32,   11,   11,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   11,   11,   43,
       11,   44,   45,   11,   46,   11,   11,   47,   48,   49,
       50,   51,   11,   11,   11,   52,   53,   54,   57,   57,
       60,   60,   60,   60,   60,   60,   62,   88,   58,   58,
       68,   68,   68,   59,   59,   69,   89,  108,   62,   71,
       70,   72,   72,   73,   71,   85,   73,   73,   73,   82,

       62,   74,   86,   90,   96,   83,   74,   99,   87,   75,
       63,  100,  101,   91,   97,  102,  161,  132,   74,  147,
      295,   98,   63,   74,  148,  162,  103,  298,  122,  104,
       60,   60,   60,  109,   63,  297,   75,  171,  171,  110,
      116,  117,  116,  118,  121,  121,  121,  300,  296,   68,
       68,   68,  184,  185,  123,   62,  295,  119,  119,  126,
      128,  128,  128,  124,  124,  164,  164,  164,  201,   71,
      129,   72,   72,   73,  272,  283,  126,   63,  285,  202,
       71,   74,   73,   73,   73,   62,  292,  129,  130,   63,
      130,  291,   74,  131,  131,  131,   62,  170,   74,  120,

      116,  117,  116,   62,  290,  125,  117,  117,  117,   74,
      168,  168,  121,  121,  121,  173,  289,  173,  288,   63,
      174,  174,  174,  128,  128,  128,  131,  131,  131,  175,
       63,  175,  122,  129,  176,  176,  176,  167,  131,  131,
      131,  215,  215,   61,   62,  208,  209,  174,  174,  174,
      129,  287,  286,  116,  117,  116,  118,  285,  169,  169,
      169,  164,  164,  164,  268,   62,  169,  169,  169,  169,
      119,  119,  174,  174,  174,  176,  176,  176,   63,  212,
      212,  169,  169,  169,  169,  169,  169,  176,  176,  176,
       63,  293,  293,  293,  282,  281,  280,  279,  278,   63,

      299,  277,  276,  275,  274,  273,  122,  272,  247,  270,
      269,  268,  120,  213,  213,  213,  293,  293,  293,  266,
      265,  213,  213,  213,  213,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  213,  213,  213,  213,
      213,  213,  245,  245,  245,  253,  252,  251,  250,  249,
      245,  245,  245,  245,  122,  122,  247,  244,  243,  242,
      241,  240,  239,  238,  237,  245,  245,  245,  245,  245,
      245,  271,  271,  271,  236,  235,  234,  233,  232,  271,
      271,  271,  271,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  271,  271,  271,  271,  271,  271,

       56,   56,   56,   56,   56,   56,   61,  220,   61,   61,
       61,   61,   65,  219,  218,   65,   66,   66,   66,  217,
       66,   66,  111,  111,  111,  111,  122,  111,  112,  112,
      112,  112,  112,  112,  114,  114,  114,  114,  114,  114,
      127,  214,  127,  127,  127,  127,  172,  211,  172,  216,
      210,  216,  246,  246,  246,  246,  246,  246,  248,  207,
      248,  267,  267,  267,  267,  267,  267,   66,  206,   66,
      284,  284,  284,  284,  284,  284,  294,  294,  294,  294,
      294,  294,  205,  204,  203,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,

      183,  182,  181,  180,  179,  178,  177,  122,  122,  166,
      165,  163,  160,  159,  158,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  146,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  134,  133,  122,  115,
      113,  107,  106,  105,   95,   94,   93,   92,   84,   81,
       80,   79,   78,   77,   76,   67,   64,  300,   55,    5,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300
    } ;

static yyconst flex_int16_t yy_chk[629] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        7,    7,    7,    8,    8,    8,    9,   40,    3,    4,
       21,   21,   21,    3,    4,   22,   40,   55,   61,   23,
       22,   23,   23,   23,   24,   39,   24,   24,   24,   37,

      118,   23,   39,   41,   46,   37,   24,   47,   39,   23,
        9,   47,   48,   41,   46,   48,  106,  309,   23,   93,
      294,   46,   61,   24,   93,  106,   48,  289,  124,   48,
       60,   60,   60,   55,  118,  288,   23,  124,  124,   55,
       63,   63,   63,   63,   64,   64,   64,   67,  287,   68,
       68,   68,  141,  141,   67,  212,  286,   63,   63,   68,
       71,   71,   71,   67,   67,  108,  108,  108,  158,   72,
       71,   72,   72,   72,  268,  268,   68,   63,  284,  158,
       73,   72,   73,   73,   73,  271,  282,   71,   74,  212,
       74,  280,   73,   74,   74,   74,  119,  121,   72,   63,

      116,  116,  116,  116,  279,   67,  117,  117,  117,   73,
      119,  119,  121,  121,  121,  126,  278,  126,  277,  271,
      126,  126,  126,  128,  128,  128,  130,  130,  130,  129,
      119,  129,  171,  128,  129,  129,  129,  116,  131,  131,
      131,  171,  171,  117,  120,  164,  164,  173,  173,  173,
      128,  273,  270,  167,  167,  167,  167,  269,  120,  120,
      120,  164,  164,  164,  267,  168,  120,  120,  120,  120,
      167,  167,  174,  174,  174,  175,  175,  175,  120,  168,
      168,  120,  120,  120,  120,  120,  120,  176,  176,  176,
      167,  283,  283,  283,  266,  265,  261,  260,  256,  168,

      293,  255,  253,  252,  251,  250,  248,  247,  246,  244,
      243,  242,  167,  169,  169,  169,  293,  293,  293,  241,
      239,  169,  169,  169,  169,  238,  237,  236,  234,  233,
      232,  231,  229,  228,  225,  224,  169,  169,  169,  169,
      169,  169,  213,  213,  213,  223,  222,  220,  219,  218,
      213,  213,  213,  213,  216,  215,  214,  211,  210,  209,
      206,  205,  204,  203,  202,  213,  213,  213,  213,  213,
      213,  245,  245,  245,  201,  200,  199,  198,  197,  245,
      245,  245,  245,  196,  195,  194,  192,  191,  190,  189,
      187,  186,  185,  184,  245,  245,  245,  245,  245,  245,

      301,  301,  301,  301,  301,  301,  302,  181,  302,  302,
      302,  302,  303,  180,  178,  303,  304,  304,  304,  177,
      304,  304,  305,  305,  305,  305,  172,  305,  306,  306,
      306,  306,  306,  306,  307,  307,  307,  307,  307,  307,
      308,  170,  308,  308,  308,  308,  310,  166,  310,  311,
      165,  311,  312,  312,  312,  312,  312,  312,  313,  163,
      313,  314,  314,  314,  314,  314,  314,  315,  162,  315,
      316,  316,  316,  316,  316,  316,  317,  317,  317,  317,
      317,  317,  161,  160,  159,  157,  156,  155,  154,  152,
      151,  150,  149,  148,  147,  146,  145,  144,  143,  142,

      140,  139,  138,  137,  135,  134,  133,  125,  123,  110,
      109,  107,  105,  104,  103,  102,  101,  100,   99,   98,
       97,   96,   95,   94,   92,   91,   90,   89,   88,   87,
       86,   85,   84,   83,   82,   81,   80,   79,   66,   59,
       58,   51,   50,   49,   45,   44,   43,   42,   38,   32,
       31,   30,   29,   27,   25,   14,   10,    5,    2,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300
    } ;

static yyconst flex_int16_t yy_rule_linenum[85] =
    {   0,
       72,   73,   74,   75,   76,   77,   78,   79,   80,   81,
       82,   83,   84,   85,   86,   87,   88,   89,   90,   91,
       92,   93,   94,   95,   96,   98,   99,  100,  101,  102,
      103,  104,  105,  106,  107,  108,  109,  110,  111,  112,
      113,  114,  115,  116,  117,  118,  119,  120,  121,  122,
      123,  124,  125,  126,  127,  128,  129,  132,  134,  138,
      143,  148,  153,  158,  163,  168,  173,  178,  182,  184,
      186,  187,  188,  191,  194,  198,  199,  201,  206,  207,
      212,  213,  214,  216
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "idl.lex"
#line 2 "idl.lex"
// import YYtokentypes;
//import YYtokentypes;

#include "IDLScanner.h"

 typedef eprosima::IDLParser::token token;
typedef eprosima::IDLParser::token_type token_type;

#define yyterminate() return token::END

/* This disables inclusion of unistd.h, which is not available under Visual C++
 * on Win32. The C++ scanner uses STL streams instead. */
#define YY_NO_UNISTD_H


//const static char LBRACE = '{';
//const static char RBRACE = '}';
 int comment_depth = 0;

/* enable c++ scanner class generation */
/* change the name of the scanner class. results in "ExampleFlexLexer" */
/*%option prefix="Example"  */
/* the manual says "somewhat more optimized" */
/* enable scanner to generate debug output. disable this for release
* versions. */
/* no support for include files is planned */
/* enables the use of start condition stacks */
/* The following paragraph suffices to track locations accurately. Each time
 * yylex is invoked, the begin position is moved onto the end position. */
#line 46 "idl.lex"
#define YY_USER_ACTION  yylloc->columns(yyleng);

#line 777 "IDLScanner.cc"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#include <unistd.h>
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */
/* %if-bison-bridge */
/* %endif */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */
/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define ECHO LexerOutput( yytext, yyleng )
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
\
/* %if-c++-only C++ definition \ */\
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#define YY_FATAL_ERROR(msg) LexerError( msg )
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define YY_DECL int yyFlexLexer::yylex()
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 64 "idl.lex"


// reset location
 yylloc->step();


#line 950 "IDLScanner.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyin = & std::cin;
/* %endif */

		if ( ! yyout )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyout = & std::cout;
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 301 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 300 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				std::cerr << "--scanner backing up\n";
			else if ( yy_act < 85 )
				std::cerr << "--accepting rule at line " << yy_rule_linenum[yy_act] <<
				         "(\"" << yytext << "\")\n";
			else if ( yy_act == 85 )
				std::cerr << "--accepting default rule (\"" << yytext << "\")\n";
			else if ( yy_act == 86 )
				std::cerr << "--(end of buffer or a NUL)\n";
			else
				std::cerr << "--EOF (start condition " << YY_START << ")\n";
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 72 "idl.lex"
{ return(token::RESOLVE_TOKEN); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 73 "idl.lex"
{ return(token::SHIFTLEFT_TOKEN); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 74 "idl.lex"
{ return(token::SHIFTRIGHT_TOKEN); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 75 "idl.lex"
{ return static_cast<token_type>(*yytext);} 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 76 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return(LBRACE);*/ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 77 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return(RBRACE);*/ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 78 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return(':');*/ }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 79 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return(',');*/ }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 80 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('='); */}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 81 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('+');*/ }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 82 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('-');*/ }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 83 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('(');*/ }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 84 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return(')');*/ }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 85 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('<');*/ }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 86 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('>'); */}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 87 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('['); */}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 88 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return(']'); */}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 89 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('\"'); */}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 90 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('\\'); */}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 91 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('|'); */}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 92 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('^'); */}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 93 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('&');*/ }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 94 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('*'); */}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 95 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('/'); */}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 96 "idl.lex"
{ return static_cast<token_type>(*yytext);/*return('%'); */}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 98 "idl.lex"
{ return(token::ANY_TOKEN); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 99 "idl.lex"
{ return(token::ATTRIBUTE_TOKEN); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 100 "idl.lex"
{ return(token::BOOLEAN_TOKEN); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 101 "idl.lex"
{ return(token::CASE_TOKEN); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 102 "idl.lex"
{ return(token::CHAR_TOKEN); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 103 "idl.lex"
{ return(token::CONST_TOKEN); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 104 "idl.lex"
{ return(token::CONTEXT_TOKEN); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 105 "idl.lex"
{ return(token::DEFAULT_TOKEN); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 106 "idl.lex"
{ return(token::DOUBLE_TOKEN); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 107 "idl.lex"
{ return(token::ENUM_TOKEN); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 108 "idl.lex"
{ return(token::EXCEPTION_TOKEN); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 109 "idl.lex"
{ return(token::FLOAT_TOKEN); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 110 "idl.lex"
{ return(token::IN_TOKEN); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 111 "idl.lex"
{ return(token::INOUT_TOKEN); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 112 "idl.lex"
{ return(token::INTERFACE_TOKEN); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 113 "idl.lex"
{ return(token::LONG_TOKEN); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 114 "idl.lex"
{ return(token::MODULE_TOKEN); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 115 "idl.lex"
{ return(token::OCTET_TOKEN); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 116 "idl.lex"
{ return(token::ONEWAY_TOKEN); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 117 "idl.lex"
{ return(token::OUT_TOKEN); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 118 "idl.lex"
{ return(token::RAISES_TOKEN); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 119 "idl.lex"
{ return(token::READONLY_TOKEN); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 120 "idl.lex"
{ return(token::SEQUENCE_TOKEN); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 121 "idl.lex"
{ return(token::SHORT_TOKEN); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 122 "idl.lex"
{ return(token::STRING_TOKEN); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 123 "idl.lex"
{ return(token::STRUCT_TOKEN); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 124 "idl.lex"
{ return(token::SWITCH_TOKEN); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 125 "idl.lex"
{ return(token::TYPEDEF_TOKEN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 126 "idl.lex"
{ return(token::UNSIGNED_TOKEN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 127 "idl.lex"
{ return(token::UNION_TOKEN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 128 "idl.lex"
{ return(token::VOID_TOKEN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 129 "idl.lex"
{ return(token::OBJECT_TOKEN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 132 "idl.lex"
{yyval->integerVal = 1;
			 return(token::BOOLEAN_LITERAL); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 134 "idl.lex"
{ yyval->integerVal = 0;
			return(token::BOOLEAN_LITERAL); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 138 "idl.lex"
{ /* identifier */
		yyval->stringVal = new std::string(yytext,yyleng);
		return(token::IDENTIFIER);
		}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 143 "idl.lex"
{/* octal */
		yyval->integerVal = atoi(yytext);
		return(token::INTEGER_LITERAL); 
		}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 148 "idl.lex"
{ /* decimal */
		yyval->integerVal = atoi(yytext);
		return(token::INTEGER_LITERAL);
		}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 153 "idl.lex"
{ /* hex */
		yyval->integerVal = strtol (yytext,NULL,0);
		return(token::INTEGER_LITERAL);
		}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 158 "idl.lex"
{ /* float 0.e0 */
	yyval->doubleVal = atof(yytext);
		return(token::FLOAT_LITERAL);
		}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 163 "idl.lex"
{ /* float .0e0 */
yyval->doubleVal = atof(yytext);
		return(token::FLOAT_LITERAL);
		}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 168 "idl.lex"
{ /* float 0e-0 */
yyval->doubleVal = atof(yytext);
		return(token::FLOAT_LITERAL);   
		}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 173 "idl.lex"
{ /* quoted char */
		yyval->stringVal = new std::string(yytext,yyleng);
		return(token::CHARACTER_LITERAL);
		}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 178 "idl.lex"
{ /* string */
		yyval->stringVal = new std::string(yytext,yyleng);
		return(token::STRING_LITERAL);
		}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 182 "idl.lex"
{ std::cerr << "Error" << std::endl;/*yyerror("unclosed string");*/}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 184 "idl.lex"
{ yylloc->step();/*  eliminate white space  */ }
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 186 "idl.lex"
{ return(token::PRAGMA_INFO);}
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 187 "idl.lex"
{ return(token::IDENT_INFO);}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 188 "idl.lex"
{ 
		return(token::LINE_AND_FILE_INFO);
		}
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 191 "idl.lex"
{
		return(token::LINE_AND_FILE_INFO);
		}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 194 "idl.lex"
{
		return(token::LINE_AND_FILE_INFO);
		}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 198 "idl.lex"
{ /*   uni-line comment */ }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 199 "idl.lex"
{ BEGIN(COMMENT); comment_depth++;  }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 201 "idl.lex"
{ std::cerr << "Error" << std::endl;/* yyerror("Illegal character: ");*/}
	YY_BREAK


case 79:
YY_RULE_SETUP
#line 206 "idl.lex"
{ /* begin nested multiline comment */ comment_depth++; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 207 "idl.lex"
{ /* end multiline comment */
		comment_depth--;
		if (comment_depth == 0) { BEGIN(INITIAL); }
		}
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 212 "idl.lex"
{}
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 213 "idl.lex"
{}
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 214 "idl.lex"
{}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 216 "idl.lex"
{ std::cerr << "Error" << std::endl;/*yyerror("Illegal character in comment ");*/ }
	YY_BREAK

case 85:
YY_RULE_SETUP
#line 219 "idl.lex"
ECHO;
	YY_BREAK
#line 1538 "IDLScanner.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = 0;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree(yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree(yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if ( new_in )
		{
		yy_delete_buffer( YY_CURRENT_BUFFER );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );
		}

	if ( new_out )
		yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout->write( buf, size );
}
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
int yyFlexLexer::yy_get_next_buffer()
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_get_previous_state()
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 301 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 301 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 300);

	return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyunput( int c, register char* yy_bp)
/* %endif */
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yyinput()
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
/* %if-c-only */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyrestart( std::istream* input_file )
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_load_buffer_state()
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* %if-c-only */
/* %endif */

/* %if-c++-only */

extern "C" int isatty (int );

/* %endif */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_is_interactive = 0;
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypop_buffer_state (void)
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yyensure_buffer_stack(void)
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_push_state( int new_state )
/* %endif */
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_pop_state()
/* %endif */
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yy_top_state()
/* %endif */
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::LexerError( yyconst char msg[] )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* %if-reentrant */
/* %endif */
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 219 "idl.lex"



 
 namespace eprosima {
 
 IDLScanner::IDLScanner(std::istream* in, std::ostream* out): yyFlexLexer(in, out)
 {
 }
 
 IDLScanner::~IDLScanner()
 {
 }
 
 void IDLScanner::set_debug(bool b)
 {
     yy_flex_debug = b;
 }
 
 }
 
 /* This implementation of ExampleFlexLexer::yylex() is required to fill the
  * vtable of the class ExampleFlexLexer. We define the scanner's main yylex
  * function via YY_DECL to reside in the Scanner class instead. */
 
 #ifdef yylex
 #undef yylex
 #endif
 
int yyFlexLexer::yylex()
{
     std::cerr << "in IDLFlexLexer::yylex() !" << std::endl;
     return 0;
}
 
 /* When the scanner receives an end-of-file indication from YY_INPUT, it then
  * checks the yywrap() function. If yywrap() returns false (zero), then it is
  * assumed that the function has gone ahead and set up `yyin' to point to
  * another input file, and scanning continues. If it returns true (non-zero),
  * then the scanner terminates, returning 0 to its caller. */
 
int yyFlexLexer::yywrap()
{
     return 1;
}
 
 

