#!/usr/bin/env python3
"""Write utils/pcTests/baseline.txt, a snapshot of what the recorder produces today.

check_monitor_schema.py asserts the facts that must hold; this records everything else, so a
change that shifts a row count or a column order somewhere no assertion covers still shows up
as a diff.  Regenerate it deliberately, and read the diff before committing it.

Every capture is recorded twice, with and without -queryable, using the IDL file that sits
beside it.  Standard library only; the dev container has no sqlite3 CLI.
"""

import hashlib
import os
import sqlite3
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CAPTURES = os.path.join(REPO, 'utils', 'pcTests', 'capturefiles')
OUTPUT = os.path.join(REPO, 'utils', 'pcTests', 'baseline.txt')

NAMES = ['arrays', 'basic_types', 'complextype_in_sequence', 'recursive_structs',
         'sequences', 'test1', 'test2', 'unions']


def fixtures():
    for name in NAMES:
        capture = os.path.join(CAPTURES, name + '.pcap')
        idl = os.path.join(CAPTURES, name + '.idl')
        yield capture, (idl if os.path.exists(idl) else None), name
    yield (os.path.join(REPO, 'examples', 'HelloWorld', 'HelloWorld.pcap'),
           os.path.join(REPO, 'examples', 'HelloWorld', 'HelloWorld.idl'),
           'HelloWorld')


def snapshot(db, out):
    connection = sqlite3.connect('file:%s?mode=ro' % db, uri=True)
    try:
        for kind in ('table', 'view', 'index'):
            names = sorted(row[0] for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type = ? AND name NOT LIKE 'sqlite_%'",
                (kind,)))
            for name in names:
                if kind == 'index':
                    out.append('    index %s' % name)
                    continue
                cursor = connection.execute('SELECT * FROM "%s"' % name)
                columns = [d[0] for d in cursor.description]
                rows = list(cursor)
                # The blob of a sample is hashed with the rest; its bytes are not printed.
                digest = hashlib.sha256(repr(rows).encode()).hexdigest()[:16]
                out.append('    %-5s %-44s rows=%-6d sha=%s' % (kind, name, len(rows), digest))
                out.append('        cols: %s' % ','.join(columns))
    finally:
        connection.close()


def main():
    recorder = os.environ.get('DDS_RECORDER', 'dds_recorder')
    workdir = tempfile.mkdtemp(prefix='baseline_')
    out = ['# Generated by utils/pcTests/make_baseline.py. Do not edit by hand.', '']

    for capture, idl, name in fixtures():
        if not os.path.exists(capture):
            continue
        for label, extra in (('default', []), ('queryable', ['-queryable'])):
            db = os.path.join(workdir, '%s_%s.db' % (name, label))
            command = [recorder, '-db', db] + extra
            if idl:
                command += ['-idl', idl]
            command.append(capture)
            completed = subprocess.run(command, capture_output=True, text=True)
            blob = completed.stdout + completed.stderr
            packets = [l for l in blob.splitlines() if 'processed RTPS packets' in l]
            out.append('== %s [%s] %s' % (name, label, packets[-1] if packets else 'NO COUNT'))
            for line in sorted({l for l in blob.splitlines() if l.startswith('ERROR')}):
                out.append('    !! %s' % line)
            snapshot(db, out)

    with open(OUTPUT, 'w') as handle:
        handle.write('\n'.join(out) + '\n')
    print('wrote %s (%d lines)' % (OUTPUT, len(out) + 1))
    return 0


if __name__ == '__main__':
    sys.exit(main())
