/******************************************************************************************
 * Copyright (c) 2015 eProsima. All rights reserved.
 *
 * This copy of eProsima Non-Intrusive DDS Recorder is licensed to you
 * under the terms described in the DDSRECORDER_LICENSE file included in this distribution.
 *
 *****************************************************************************************/
#ifndef _TYPESTORE_H_
#define _TYPESTORE_H_

#ifdef __cplusplus

#include <map>
#include <string>

#include <fastdds/dds/xtypes/dynamic_types/DynamicType.hpp>

#include "database/TypeDescription.h"

namespace eprosima {
namespace fastdds {
namespace dds {
namespace xtypes {
// Declared rather than included: DynamicType.hpp does not bring the XTypes objects in, and the
// whole of TypeObject.hpp is a heavy include to impose on every user of this header.
class TypeIdentifier;
} // namespace xtypes
} // namespace dds
} // namespace fastdds

class eProsimaLog;

/**
 * \brief The data types the recorder knows, indexed by type name.
 *
 * The RTPS traffic carries no type description the recorder can use, so the only source is the
 * IDL file given with '-idl'. The whole file is parsed once at start up and every type declared
 * in it is kept here; a topic whose type name is not among them is recorded without a data type.
 *
 * The types are Fast DDS \c DynamicType instances. Fast DDS is used purely as a local type model,
 * CDR decoder and XTypes generator: the recorder never joins a DDS domain and never reads a
 * TypeObject off the wire. The TypeIdentifier and the TypeObject the Types.information and
 * Types.object columns hold are generated here from the type the IDL file declared, so a type
 * the file does not declare leaves both columns empty.
 */
class TypeStore
{
public:

    /**
     * \brief Constructor. Creates an empty store.
     *
     * \param log Log object used to log errors.
     */
    TypeStore(
            eProsimaLog& log);

    /**
     * \brief Parses an IDL file and keeps every type declared in it.
     *
     * Structures, unions, enumerations and aliases are all taken, so a type that is only reachable
     * through an alias resolves like any other. Parsing is all or nothing: when the file does not
     * parse the store is left empty.
     *
     * \param idl_file Path to the IDL file.
     * \return True value is returned when the file parsed and declared at least one type.
     */
    bool load(
            const std::string& idl_file);

    /**
     * \brief Looks a data type up by its name.
     *
     * \param type_name Name of the DDS Topic data type, as announced in the discovery traffic.
     * \return The data type, or a nil reference when the IDL file did not declare it.
     */
    eprosima::fastdds::dds::DynamicType::_ref_type find(
            const std::string& type_name) const;

    /**
     * \brief Renders a data type as IDL, for the 'idl' column of the Types table.
     *
     * \param type_name Name of the DDS Topic data type.
     * \return The type rendered as IDL, or an empty string when it is not known.
     */
    std::string idl_for(
            const std::string& type_name) const;

    /**
     * \brief Describes a data type the way the Types table stores it.
     *
     * The IDL rendering, the complete TypeIdentifier and the complete TypeObject, plus one entry
     * per type this one depends on. The XTypes objects are generated by registering the type in
     * the Fast DDS type object registry, which is a local operation: nothing is published and no
     * DDS domain is joined.
     *
     * \param type_name Name of the DDS Topic data type, as announced in the discovery traffic.
     * \return The description, with every member empty when the IDL file did not declare the type.
     * The reference is owned by the store and stays valid for as long as it does.
     */
    const TypeDescription& describe(
            const std::string& type_name) const;

    /**
     * \brief Whether a data type has any member marked as a key.
     *
     * Keyedness is a property of the data type, and no RTPS discovery message states it, so the
     * IDL file is the only place it can come from.
     *
     * \param type_name Name of the DDS Topic data type.
     * \return True when the type is known and declares at least one key member.
     */
    bool is_keyed(
            const std::string& type_name) const;

    /// Number of types the IDL file declared.
    size_t size() const;

private:

    eProsimaLog& log_;

    std::map<std::string, eprosima::fastdds::dds::DynamicType::_ref_type> types_;

    /**
     * The IDL of each type as idl_for() rendered it, kept so that it is rendered once.
     *
     * idl_for() is called for every endpoint announcement in a capture, and a system re-announces
     * its endpoints for as long as it runs, while the result is wanted only the first time: the
     * Types row is written with INSERT OR IGNORE. Rendering walks the whole type and builds a
     * string, so it is much the most expensive thing done per discovery packet.
     *
     * Mutable because the memo is not part of the observable state: idl_for() is const, and a
     * type name that is not known caches an empty string so that it is not retried either.
     */
    mutable std::map<std::string, std::string> idl_cache_;

    /**
     * \brief Fills the XTypes members of a description from a data type.
     *
     * \param type_name Name of the data type, used to report an error.
     * \param type The data type.
     * \param description Description to fill in. Left as it was when the type cannot be generated.
     */
    void generate_xtypes(
            const std::string& type_name,
            const eprosima::fastdds::dds::DynamicType::_ref_type& type,
            TypeDescription& description) const;

    /**
     * \brief Adds one entry to a description per type the described type is built from.
     *
     * \param type_name Name of the described data type, used to report an error.
     * \param identifier The complete TypeIdentifier of the described data type.
     * \param description Description to add the dependencies to.
     */
    void generate_dependencies(
            const std::string& type_name,
            const eprosima::fastdds::dds::xtypes::TypeIdentifier& identifier,
            TypeDescription& description) const;

    /**
     * The description of each type, kept for the same reason as \c idl_cache_.
     *
     * Generating it registers the type and serializes two XTypes objects, which is far more work
     * than the discovery packet that asks for it deserves to do again. A type name that is not
     * known caches an empty description, so it is not retried either.
     */
    mutable std::map<std::string, TypeDescription> description_cache_;
};
} // namespace eprosima

#endif // ifdef __cplusplus

#endif // _TYPESTORE_H_
